name: Create Release Branch

on: 
  workflow_dispatch:
    inputs: 
      version: 
        description: test
        default: teste

jobs: 
  create-release:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Script 
        run: |
          chmod +x ./scripts/release-branch.sh
          ./scripts/release-branch.sh