name: Create Release Branch

on: 
  workflow_dispatch:
    inputs:
      version: 
        description: Test
        default: "48.23.0"

jobs: 
  create-release:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Git configuration
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create Tag
        run: | 
          git tag v1.0.0
          git push origin v1.0.0

      - name: Execute Script 
        run: |
          chmod +x ./scripts/release-branch.sh
          ./scripts/release-branch.sh