name: Teste

on: 
  workflow_dispatch:
    inputs: 
      version: 
        description: test
        default: testando

jobs: 
  create-release:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Script 
        run: echo ${{ inputs.version.default }}