name: Teste

on: 
  workflow_dispatch:
    inputs: 
      version: 
        description: test
        default: daily-android-sdx-1234

jobs: 
  create-release:
    if: ${{ github.event.inputs.version == daily-android-sdx-1234 }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Script
        run: |
          echo "${{ github.event.inputs.version }} TESTE CONCLUIDO"
