name: Create Release Branch

on: 
  workflow_dispatch:
    inputs:
      version: 
        description: Test
        default: v1.0.0

jobs: 
  create-release:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag
        run: | 
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Execute Script 
        run: |
          chmod +x ./scripts/release-branch.sh
          ./scripts/release-branch.sh